### ISSUE TITLE
Analytics code

### ISSUE THREAD

**Issue by 2pha** [yutatoga/shader#1]
Please remove my google analytics code from the files in this repository.

**Comment by 2pha** [comment]
![my_analytics_code](https://user-images.githubusercontent.com/2011816/46576998-66103280-ca1d-11e8-94b9-0c53600446fc.gif)

**Comment by yuta-toga** [comment]
Sorry!! I removed.  Thank you so much for your blog, I learned a lot from there!

**Comment by 2pha** [comment]
No worries, I am glad you found it useful
